# Generated by Django 2.1.5 on 2019-01-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='userDetails',
        ),
    ]
